Repository ipfs/ipfs-webui, pull requests merged in 2018-07, with the labels that each got.

#695 fix: disable onClick on inactive buttons
  src/files/selected-actions/SelectedActions.js
Labels: bug, difficulty:easy, revamp

#696 fix: issues when multiple files on the same dir have the same hash
  src/bundles/files.js
  src/files/FilesPage.js
  src/files/file/File.js
  src/files/files-list/FilesList.js
Labels: bug, revamp

#697 feat: overlay component
  src/files/FilesPage.js
  src/files/overlay/Overlay.js
Labels: revamp

#691 feat: download files
  src/bundles/files.js
  src/bundles/ipfs.js
  src/files/FilesPage.js
  src/files/files-list/FilesList.js
  src/files/selected-actions/SelectedActions.js
Labels: in progress, revamp

#699 chore: update dependencies
  package-lock.json
  package.json
Labels: revamp

#684 Settings page config editor
  .storybook/addons.js
  package-lock.json
  package.json
  src/bundles/config-save.js
  src/bundles/config.js
  src/bundles/index.js
  src/bundles/routes.js
  src/components/box/Box.js
  src/components/button/Button.css
  src/components/button/Button.js
  src/components/button/Button.stories.js
  src/loader/ComponentLoader.js
  src/loader/ComponentLoader.stories.js
  src/navigation/NavBar.js
  src/navigation/NavBar.stories.js
  src/settings/LoadableSettingsPage.js
  src/settings/SettingsPage.js
  src/settings/SettingsPage.stories.js
  src/settings/editor/JsonEditor.js
  src/settings/editor/JsonEditor.stories.js
  src/settings/editor/fixtures/example-config.json
  src/settings/editor/theme/ipfs_dark.js
  test/e2e/navigation.test.js
Labels: revamp

#705 feat: clickable icons on file browser
  src/files/file/File.js
Labels: revamp

#703 feat: add folder
  package-lock.json
  package.json
  src/bundles/files.js
  src/files/FilesPage.js
  src/files/file-input/FileInput.js
  src/files/files-list/FilesList.js
  src/lib/path.js
Labels: revamp

#706 refactor: more generic modal component
  package-lock.json
  src/files/FilesPage.js
  src/files/delete-modal/DeleteModal.js
  src/files/delete-modal/DeleteModal.stories.js
  src/files/delete-prompt/DeletePrompt.stories.js
  src/files/modal/Modal.js
  src/files/rename-modal/RenameModal.js
  src/files/rename-modal/RenameModal.stories.js
  src/files/rename-prompt/RenamePrompt.js
Labels: revamp

#707 Improve ObjectInfo data inspector
  package-lock.json
  package.json
  src/explore/graph/IpldGraphCytoscape.js
  src/explore/object-info/ObjectInfo.js
  src/lib/cid.js
  src/lib/dag.js
  src/lib/dag.test.js
  src/lib/path.js
Labels: revamp

#709 💄: make dropdown look better
  package-lock.json
  package.json
  src/files/file-input/FileInput.js
Labels: revamp

#708 feat: add by path
  package-lock.json
  package.json
  src/bundles/files.js
  src/components/modal/Modal.js
  src/components/overlay/Overlay.js
  src/components/text-input-modal/TextInputModal.js
  src/files/FilesPage.js
  src/files/delete-modal/DeleteModal.js
  src/files/file-input/ByPathModal.js
  src/files/file-input/FileInput.js
  src/files/rename-modal/RenameModal.js
  src/index.css
Labels: revamp

#713 fix: error when moving page if items were selected
  src/files/FilesPage.js
Labels: revamp

#714 feat: validate renaming
  src/components/text-input-modal/TextInputModal.js
  src/files/rename-modal/RenameModal.js
Labels: revamp

#716 fix: utf8 characters on file names
  src/files/files-list/FilesList.js
Labels: revamp

#719 refactor: use pull streams to add files
  package-lock.json
  package.json
  src/bundles/files.js
Labels: in progress, revamp

#721 feat: new folder
  src/files/FilesPage.js
  src/files/file-input/FileInput.js
  src/files/file-input/NewFolderModal.js
  src/files/file/File.js
Labels: in progress, revamp

#717 feat: truncate text and add tooltip on hover
  src/files/file/File.js
Labels: in progress, revamp

#723 💄: files tweaks
  package-lock.json
  package.json
  src/bundles/files.js
  src/files/FilesPage.js
  src/files/breadcrumbs/Breadcrumbs.css
  src/files/breadcrumbs/Breadcrumbs.js
  src/files/file-icon/FileIcon.js
  src/files/file-input/FileInput.js
  src/files/file-preview/FilePreview.js
  src/files/file/File.css
  src/files/file/File.js
  src/files/files-list/FilesList.js
  src/files/selected-actions/SelectedActions.js
  src/files/tooltip/Tooltip.js
  src/icons/GlyphDocGeneric.js
Labels: in progress, revamp

#702 feat: add peer locations bundle
  package-lock.json
  package.json
  src/bundles/index.js
  src/bundles/peer-locations.js
  src/bundles/peer-locations.test.js
  src/status/PeerBandwidthTable.js
  test/helpers/ip.js
Labels: in progress, revamp

#731 💄: explore tweaks
  package-lock.json
  src/components/tooltip/Tooltip.js
  src/explore/StartExploringPage.js
  src/files/file/File.js
Labels: in progress, revamp

#726 feat: peers page
  package-lock.json
  package.json
  src/bundles/peer-locations.js
  src/bundles/peers.js
  src/peers/PeersPage.js
  src/peers/PeersTable/PeersTable.js
  src/peers/WorldMap/WorldMap.js
  src/peers/WorldMap/world.json
Labels: in progress, revamp

#729 feat: drag'n'drop files
  package-lock.json
  package.json
  src/App.js
  src/bundles/files.js
  src/components/checkbox/Checkbox.css
  src/components/checkbox/Checkbox.js
  src/files/FilesPage.js
  src/files/download-file.js
  src/files/file/File.css
  src/files/file/File.js
  src/files/files-list/FilesList.js
  src/files/selected-actions/SelectedActions.js
  src/lib/dnd-backend.js
Labels: in progress, revamp

#710 feat: navbar width toggle
  src/App.js
  src/navigation/NavBar.js
  src/navigation/NavBar.stories.js
  src/navigation/ipfs-logo-text.svg
  src/navigation/ipfs-logo.svg
Labels: in progress, revamp

#720 feat: context menu
  package-lock.json
  package.json
  src/components/checkbox/Checkbox.css
  src/files/FilesPage.js
  src/files/breadcrumbs/Breadcrumbs.css
  src/files/breadcrumbs/Breadcrumbs.js
  src/files/context-menu/ContextMenu.js
  src/files/context-menu/ContextMenu.stories.js
  src/files/dropdown/Dropdown.js
  src/files/file-input/FileInput.js
  src/files/file/File.js
  src/files/files-list/FilesList.js
  src/files/selected-actions/SelectedActions.stories.js
  src/icons/GlyphDots.js
  src/index.css
Labels: in progress, revamp
