Repository ipfs/ipfs-webui, pull requests merged in 2018-06, with the labels that each got.

#669 feat: add files page
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/bundles/files.js
  src/bundles/index.js
  src/bundles/ipfs.js
  src/bundles/routes.js
  src/files/FilesPage.js
  src/files/breadcrumbs/Breadcrumbs.js
  src/files/file-icon/FileIcon.js
  src/files/file-icon/extensions/audio.json
  src/files/file-icon/extensions/calc.json
  src/files/file-icon/extensions/image.json
  src/files/file-icon/extensions/text.json
  src/files/file-icon/extensions/video.json
  src/files/file-input/FileInput.js
  src/files/file-preview/FilePreview.js
  src/files/files-list/FilesList.js
  src/files/selected-actions/SelectedActions.js
  src/files/type-from-ext/extToType.js
  src/files/type-from-ext/index.js
  src/lib/path.js
  src/navigation/NavBar.js
Labels: revamp

#673 chore: update dependencies
  package-lock.json
  package.json
Labels: revamp

#674 fix: travis badge url, add david badge, use consistent badge style
  README.md
Labels: in progress, revamp

#678 chore: extract e2e test from unit tests
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/App.test.js
  src/files/FilesPage.js
  src/ipld/IpldPage.js
  src/peers/PeersPage.js
  src/settings/SettingsPage.js
  src/status/StatusPage.js
  test/e2e/navigation.test.js
  test/e2e/puppeteer.js
Labels: revamp

#672 feat: IPLD graph for explore page
  package-lock.json
  package.json
  src/App.js
  src/bundles/explore.js
  src/bundles/index.js
  src/bundles/object.js
  src/bundles/routes.js
  src/components/cid/Cid.js
  src/components/cid/Cid.stories.js
  src/explore/ExplorePage.js
  src/explore/IpldExploreForm.js
  src/explore/cid-info/CidInfo.js
  src/explore/cid-info/CidInfo.stories.js
  src/explore/graph-crumb/GraphCrumb.js
  src/explore/graph-crumb/GraphCrumb.stories.js
  src/explore/graph/IpldGraph.js
  src/explore/graph/IpldGraph.stories.js
  src/explore/graph/IpldGraphCytoscape.js
  src/explore/object-info/ObjectInfo.js
  src/explore/object-info/ObjectInfo.stories.js
  src/explore/object-info/fixtures/object-info-0-links.json
  src/explore/object-info/fixtures/object-info-1240-links.json
  src/explore/object-info/fixtures/object-info-36-links.json
  src/explore/object-info/fixtures/object-info-8-links.json
  src/ipld/IpldPage.js
  src/ipld/graph/IpldGraph.stories.js
  src/ipld/object-info/fixtures/object-info-1240-links.json
  src/ipld/object-info/fixtures/object-info-36-links.json
  src/ipld/object-info/fixtures/object-info-8-links.json
  src/lib/cbor.js
  src/lib/cbor.test.js
  src/lib/cid.js
  src/lib/dag.js
  src/lib/dag.test.js
  src/lib/path.js
  src/lib/path.test.js
  src/loader/Loader.js
Labels: in progress, revamp

#680 Make linting work
  config/webpack.config.prod.js
  package-lock.json
  package.json
  src/components/checkbox/Checkbox.stories.js
Labels: ready, revamp

#681 fix: makes sidebar full height in firefox
  src/App.js
Labels: revamp

#687 feat: add rename prompt to file browser
  package-lock.json
  package.json
  src/files/FilesPage.js
  src/files/rename-prompt/RenamePrompt.js
Labels: revamp

#683 feat: add peer bandwidth bundle
  package-lock.json
  package.json
  src/bundles/index.js
  src/bundles/peer-bandwidth.js
  src/bundles/peer-bandwidth.test.js
  src/status/PeerBandwidthTable.js
  src/status/StatusPage.js
  test/helpers/cid.js
  test/helpers/random.js
  test/helpers/sleep.js
Labels: revamp

#677 feat: delete prompt component
  package-lock.json
  package.json
  src/files/delete-prompt/DeletePrompt.js
  src/files/delete-prompt/DeletePrompt.stories.js
  src/icons/GlyphTrash.js
  src/icons/StrokeTrash.js
  src/index.js
Labels: revamp

#688 feat: add node bandwidth chart to status page
  package-lock.json
  package.json
  src/bundles/index.js
  src/bundles/node-bandwidth-chart.js
  src/bundles/node-bandwidth-chart.test.js
  src/bundles/node-bandwidth.js
  src/bundles/peer-bandwidth.test.js
  src/status/NodeBandwidthChart.js
  src/status/StatusPage.js
  test/helpers/bandwidth.js
Labels: revamp

#689 feat: add delete prompt to file browser
  package-lock.json
  src/files/FilesPage.js
  src/files/files-list/FilesList.js
  src/index.css
Labels: revamp

#692 fix: input focus
  src/files/rename-prompt/RenamePrompt.js
Labels: bug, difficulty:easy, revamp

#693 fix: navigation for encoded names
  src/bundles/files.js
  src/files/FilesPage.js
Labels: revamp
