Repository ipfs/ipfs-webui, pull requests merged in 2018-08, with the labels that each got.

#732 feat: cache peer locations for 1 week
  package-lock.json
  package.json
  src/bundles/cache.js
  src/bundles/peer-locations.js
Labels: in progress, revamp

#741 💄: more file browser tweaks
  src/bundles/files.js
  src/components/checkbox/Checkbox.css
  src/components/checkbox/Checkbox.js
  src/components/checkbox/Checkbox.stories.js
  src/components/progress-bar/ProgressBar.js
  src/components/progress-bar/ProgressBar.stories.js
  src/files/FilesPage.js
  src/files/context-menu/ContextMenu.js
  src/files/file-icon/FileIcon.js
  src/files/file-input/FileInput.js
  src/files/file/File.css
  src/files/file/File.js
  src/files/files-list/FilesList.css
  src/files/files-list/FilesList.js
  src/files/progress-bar/ProgressBar.css
  src/files/selected-actions/SelectedActions.css
  src/files/selected-actions/SelectedActions.js
  src/files/status/Status.js
  src/index.css
  src/lib/files.js
Labels: in progress

#754 feat: home icon on breadcrumbs
  package-lock.json
  package.json
  src/files/breadcrumbs/Breadcrumbs.js
  src/icons/GlyphHome.js
Labels: in progress, revamp

#753 feat: arrow navigation
  src/components/overlay/Overlay.js
  src/files/files-list/FilesList.js
Labels: in progress, revamp

#759 feat: files focus mode
  src/bundles/files.js
  src/components/checkbox/Checkbox.css
  src/files/file/File.js
  src/files/files-list/FilesList.js
Labels: in progress, revamp

#761 More files polishing
  package-lock.json
  src/bundles/files.js
  src/files/FilesPage.js
  src/files/breadcrumbs/Breadcrumbs.js
  src/files/file/File.js
Labels: in progress, revamp

#763 feat: change can't preview message and add loading animation
  src/files/file-preview/FilePreview.js
Labels: in progress, revamp

#770 feat: suggest download when preview not possible
  src/files/file-preview/FilePreview.js
Labels: revamp
